name:          Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML, CSS, and JavaScript.
url:           http://codeguide.stephentudor.com

markdown:      rdiscount
permalink:     pretty
pygments:      true
